P-H-C/phc-winner-argon2

src/core.c
Use the correct variable names in `secure_wipe_memory()`.
=> Fix secure_wipe_memory() on OpenBSD

src/run.c
The package is explicitly compiled in c89 compatiblity mode, but uses a declaration that requires c99 (which breaks at least on OpenBSD)
=> Fix compilation in c89 mode

src/core.c
instance->memory should not be a uint8_t pointer and and a block pointer at the same time.
=> Fix violation of pointer aliasing rules

src/argon2.c
Build fails with:
src/argon2.c:223:22: error: 'b2' undeclared (first use in this function)
d |= b1[i] ^ b2[i];
Addresses variable names to fix.
=> Fails to build - variable names.

src/argon2.c
I appreciate some of these values are quite small and unlikely to fail, however:
* Some of these values are caller defined and could be as large as the caller provides
* Better safe than sorry
* This makes it consistent with other malloc calls
=> Paranoid return checks on malloc.

src/run.c
The difficulty with magic numbers is that it isn't always obvious where they came from. Throwing 300 at it was assumedly guesswork, which isn't a totally safe approach (even though it turned out to be excess of requirements).
=> Document process to identify required encoding lengths.

src/core.c
If ARGON2_MIN_PWD_LENGTH is 0, the latter condition will always fail.
=> Simplify condition.

Makefile
This fix means people don't have to modify the Makefile in order to use other compilers.
=> Removing hijack of $CC

src/opt.c, src/ref.c
Harmless here, but it doesn't hurt since `fill_segment()` is supposed to be a no-op with a NULL instance.
=> Don't dereference a pointer before checking that it's not NULL

src/argon2.h
Harmless here, but it doesn't hurt since `fill_segment()` is supposed to be a no-op with a NULL instance.
=> Memory usage is m_cost KiB, not 2^m_cost KiB

Makefile
This PR alters Makefile to honour existing CFLAGS and LDFLAGS when building libraries and binaries.
Those flags are typically used for system-wide compilation tweaks.
Signed-off-by: Luca Bruno <lucab@debian.org>
=> makefile: preserve external flags

src/argon2.c
This adds a check for negative index values, preventing an index
out-of-bounds access. Closes #66
Signed-off-by: Luca Bruno <lucab@debian.org>
=> argon2: add negative index check to error_message

src/argon2.c, src/core.h, src/opt.c, src/opt.h, src/ref.c, src/ref.h
If you add some more gcc checks, like mentioned below, a lot of warnings appears.
Some are fixed with patches, some like
``comparison of unsigned expression < 0 is always false``
``comparison is always false due to limited range of data type``
are in range check code and depends on exact #defines...
(Anyway, in the current setting it is dead code because
checks are equal to uin32_t data type on input...)
I would prefer that code should avoid these warning because later
some real problem could appear and it is easy to overlook a new warning.
Tested with Makefile with these added options:
```
CFLAGS += -Wextra \
-Wsign-compare \
-Werror-implicit-function-declaration \
-Wpointer-arith \
-Wwrite-strings \
-Wswitch \
-Wmissing-format-attribute \
-Wstrict-aliasing=3 \
-Winit-self \ …
```
=> Fix/workaround some gcc  extra warnings

src/argon2.c, src/argon2.h, src/core.c, src/core.h
fill_memory_blocks() configured to return a status, this introduces checks
for a number of a different error conditions, inlcuding calloc() and NULL
pointer failures. These were previously ignored errors.
Thread failures no longer call printf/exit, ensuring better support for
higher level bindings. fill_memory_blocks() is only called in one place,
it's return value is now checked.
Implications for bindings: new error code may need dedicated handling.
This patch can be tested by setting ulimit -u and running ./argon2 with a
relevant thread count.
=> Introduces an error state for threading failures. Fixes #64.

src/argon2.c
No functional changes - but better use of existing constants reduces risk of future bugs and reads better.
=> Utilise existing constants more consistently.

src/argon2.c, src/encoding.c
C89 flags in the existing Makefile mean, this library does not built with these comments in place.
=> Remove // style comments.

src/argon2.c, src/encoding.c
Fixes #77 , and potentially several related issues stemming from inconsistent verifiers. Original patch from Libsodium.
The original patch would cause verifies, and called in run.c, to fail with ARGON2_PWD_PTR_MISMATCH, and then ARGON2_FREE_MEMORY_CBK_NULL - have introduced extra zeroing to correct this.
=> Implement verify fix from libsodium

src/bench.c, src/genkat.c
This fixes build errors in `make bench` and `make test` after low-level API refactoring in d9b0bafe37dbb94f22748b7bc73268b073e4934c.
=> Fix bench and genkat after low-level API renaming

src/argon2.c
They don't compile on older VS:
- VS9: https://ci.appveyor.com/project/hynek/argon2-cffi/build/job/mvi94cpdjil8bwyl
- VS10: https://ci.appveyor.com/project/hynek/argon2-cffi/build/job/k87gtijc1mp9sdkj
=> Remove C99-style variable declaration

README.md, include/argon2.h
A minor PR to:
* cleanup undefined methods (#84)
* reword part of the Readme (#56)
* reformat doc comments in headers, as they got garbled over time
=> Minor cleaning for header and doc

.gitignore, Makefile, README.md, src/test.c
With respect to working on #85, I'd like to suggest introducing a test suite.
The existing kats/test.sh is great at testing block internals during a hash, but leaves large parts of functionality open. I also note that the majority of recent commits and bugfixes have related to the encoding, decoding, and error management.
This test suite covers all those elements, and should integrate well with a chosen CI system. If this PR is accepted I would be happy to assist further in resolving #85 by introducing a Travis configuration.
This PR also sets CFLAGS on test compilations to utilise additional compiler warnings, and ASAN, which provides further verification against several classes of bugs.
=> Introduces an automated test suite.

.travis.yml, Makefile
Fixes #101.
Having the most strict configuration in CI ensures build quality, whilst removing less supported flags from general tests ensures portability.
Also removed -Werror from non-CI tests, to prevent total failures due to different compiler's reporting standards.
=> Make general test compile flags more relaxed than CI test case.

src/test.c
A region of code identified with no coverage relates to threaded tests.
This introduces such a test. Also test argon2_error_msg.
=> Introduce a test for multiple threaded hash.

include/argon2.h, src/argon2.c, src/test.c
Currently the `argon2_verify` function returns `ARGON2_DECODING_FAIL` for both if there was any error during the hashing (even if it was not a decoding failure) or if the password does not match with the supplied hash.
This commit makes a mismatching hash return `ARGON2_VERIFY_MISMATCH` instead, making it possible to detect if there was a failure or if the password just does not match. Additionally, it forwards the verification hashing error for better diagnostic.
There's also a test for mismatching password verification.
=> Issue different error codes for verify failure and mismatch

Makefile, README.md, src/run.c
Fixes CLI tool to handle salts with length different than 16 and hash output length different than 32. Current behavior is to force salts to be 16 bytes long and pad if shorter and hash is hardcoded to 32 bytes. Updated behavior is:
```bash
$ echo -n "password" | ./argon2 somesaltextremelylargerthanexpectedmuchmuchlargerthanpreviouslywasallowed -t 2 -m 16 -p 4 -h 512
Type:		Argon2i
Iterations:	2 
Memory:		65536 KiB
Parallelism:	4 
Hash:		37d0a5e731f1c57966c2cd35c57597721c6d35d2dd07b5cdb14e306aba2e433587adc792e965a40be4f871d4fa9373563a08321654da2d2aa060bf941e380889cfa059686176c4e24bf0af1f7329016ded5dd8903f582cb773f5ca09cbf163db924baca32a2c131b6313fcd7c12fa03192c08fd5efee37c4a4cd675c7cbbf683ef87f61229e0fc0e720b03c16cae3fa10910437ad3b81165a156cab5e6691b1ba513e1e57d36c670b5334f5d4d4341603f80a9 …
```
=> Fix cli tool to handle variable length salts

Makefile
There are currently a number of issues with the OPT parameter.
- As far as I can see, it's undocumented. I only know about it because I did some work in the Makefile.
- The fact it just refers to "optimisations" and not "x86 specific optimisations" can be confusing
- Releases and distributions are forced to either utilise the flag, and write apps that are x86 specific, or not use the flag, and release suboptimal code.
- This led to #112.
- The majority of bindings have utilised the path of least resistance and not used this flag at all
- This means the majority of deployments are not using the optimised path
- Slower code may lead to reduced work strengths than servers are suited for
This change aims to work around it. The logic looks backwards - but I've tested on EC2 (x86_64) and …
=> Utilise OPT on supported platforms.

Makefile, src/test.c
The m=20 test burns a GB of RAM. On an EC2 instance with only 512MB RAM, this test runs mostly in swap space, and runs for over 40 minutes. Obviously, this is undesirable.
=> Remove test with m=20, as it takes too much RAM for many devices.

src/thread.c
Capitalized Windows.h breaks on MinGW. "windows.h" is the proper include.
=> Include lower-case "windows.h"

src/run.c
The current read loop overwrites the buffer in a circular fashion, producing obvious issues. The following two commands produce identical output, which is obviously dangerous for a password hashing function:
$ ruby -e "print 'a'*130" | ./argon2 somesalt -t 2 -m 16 -p 4 -h 24
$ ruby -e "print 'a'*3" | ./argon2 somesalt -t 2 -m 16 -p 4 -h 24
Without delving into the complication of dynamic buffers, and given this only reads from stdin rather than a socket, I'm proposing a more simple solution is suited.
=> Improve handling of long passwords for command line utility.

src/argon2.c
argon2_verify creates an argon2_context, and configures a number of elements before passing it to decode_string. There, pwdlen is set to 0 and it is passed to validate_inputs.
There, pwd is used in a comparison as an uninitialized variable.
=> Properly zero pwd pointed before using it.

man/argon2.1
I'm forwarding this manpage which has been submitted to Debian bug tracker:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820491
=> argon2: add manpage with usage info

src/argon2.c
It turns out calling memset() with n == 0 is undefined behaviour. This is discussed here:
http://stackoverflow.com/questions/8597034/can-memset-be-called-with-a-null-pointer-if-the-size-is-0
[tis-interpreter](https://github.com/TrustInSoft/tis-interpreter) has identified that the codebase does currently make such a call.
I cannot find definitive information regarding the other functions, however:
- I presume memset_s behaves the same
- [this discussion](https://gcc.gnu.org/ml/gcc/2015-09/msg00135.html) seems to suggest explicit_bzero should check for n == 0
- There is no suggestion anywhere that SecureZeroMemory behaves this way, that I can find
The implementation is messier than I would like - because simply placing this check at the start of the function messes with C89 compliance, …
=> Ensure memset is not called with n == 0. This is undefined in C.

README.md
The example in the README is out of date with regards to the argon2_context. I have also updated it to demonstrate safely checking return values, and added comments explaining fields.
=> Update README example code with newer context struct and function names.

Makefile
Fixed the makefile so that argon2 is compilable on Windows with MSYS2.
=> Compile on Windows with MSYS2

libargon2.pc
This is a pkg-config template to be used as a common base by downstream installers. Not used by us directly, as we don't provide any `install` target.
=> libargon2: add a pkg-config stub

README.md, man/argon2.1, src/run.c
This commit adds `-h` as a command line option to display usage info, moving the existing hash length switch to `-l`.
This is a breaking change for existing scripts using `-h`.
=> run: use `-h` as command line option for usage help

Makefile
Consolidate FreeBSD, NetBSD, and OpenBSD in Makefile since they all use the same flags.
=> Consolidate FreeBSD, NetBSD, and OpenBSD in Makefile

include/argon2.h
While previously Visual Studio would build the project just fine, the result would produce no exports, meaning that it would be useless as this is a library.
=> Add support for building DLLs with Visual Studio

src/core.c
In the original code, the contents of the allocated memory are copied to instance->memory instead of the actual pointer value. This patch fixes the bug and also simplifies the code.
=> Fix bad pointer copy when using custom allocator

Makefile
This commit allows passing an explicit OPTTARGET as the target
architecture for checking optimization capabilities.
This is needed for reataining compatibility to a baseline when
ditributing binaries.
For reference: https://bugs.debian.org/828779
=> makefile: optional explicit target for optimizations

README.md
Hello!
I've compiled Argon2 for browsers with asm.js and WebAssembly, please add my port to ports list.
=> add javascript browser port

src/blake2/blake2-impl.h, src/blake2/blake2b.c
Both burn() and secure_wipe_memory() serve identical functions.
This patch addresses code reuse. I also have the following concerns about the existing code:
- burn() does not have the NOT_OPTIMIZED attribute. 
- burn() does not OpenBSD or Windows specific variants
I'm unsure how important some of these are, but discrepancies like this are a good reason to reuse functions. I don't *think* it matters that a prototype doesn't use the attribute, since nothing is compiled there.
=> Eliminate redundant function.

Makefile, README.md
This adds an install target to the makefile, making it easier to install or package Argon2
=> Add install target

LICENSE, Makefile, README.md, include/argon2.h, man/argon2.1, src/argon2.c, src/bench.c, src/core.c, src/core.h, src/encoding.c, src/encoding.h, src/genkat.c, src/genkat.h, src/opt.c, src/opt.h, src/ref.c, src/ref.h, src/run.c, src/test.c, src/thread.c, src/thread.h
For reasons similar to why OpenSSL needed BLAKE2 to be triple-licensed, it would be helpful to software devs within Google if Argon2 were available under the Apache 2.0 license.
This PR adds the text of the Apache 2.0 license to the LICENCE file, modifies the headers to explain the nature of the dual license, and adds all four contributors to the copyright notice.
=> License change

README.md
Include my new library in the Bindings section.
To be fair, it is just a proxy to the argon2 lib by @ranisalt. However, argon2themax includes a bench-like utility which will automatically choose the most costly Argon2 options within a given clock time ceiling. This allows engineers to easily choose an option that is more secure than the default on whatever system they are running on and still maintain a good user experience.
For instance, you can ask for an option set that takes up to 100ms to run, and the library will march through increasingly costly options to find a set that hits as close to 100ms, without going over, as possible.
Since it isn't strictly a new binding maybe there should be another section in the README for stuff like this?
=> Add argon2themax binding

src/core.c
This patch fixes memory leak of a localy heap allocated 'threads' variable in fill_memory_blocks().
The leak happens in case of failure of argon2_thread_join(), needed to wait end of just created threads.
=> fix memory leak in fill_memory_blocks

src/core.c, src/encoding.c, src/test.c
I significantly constrained the space of admissible encodings to deal with #143 . 
The `keyid` and `data` parameters in the encoding are gone, as they are either not used in validation, or they cause validation to fail. Similarly, the salt is now required. Before if no salt was provided, the encoding wouldn't include the salt or the hash value. Because there was no hash value, any later validation check would fail.
I also made changes to `validate_context`. Empty vs. `NULL` passwords and salts now produce the same results and errors. The salt was the real outlier here, a `NULL` salt was allowed while an empty salt produced an error (`ARGON2_SALT_TOO_SHORT`). This is inconsistent with the rest of Argon2, where switching a  parameter from empty to `NULL` produces the exact same hash value …
=> Fixed up encoding issues

src/opt.c, src/opt.h, src/ref.c, src/ref.h
This PR attempts to de-duplicate and simplify the code for the fill_segment function and its helper functions.
Summary of changes:
- fill_block and fill_block_with_xor are merged into a single function
- fill_block in opt.c now accepts block pointers instead of uint8_t pointers
- Argon2i pseudo-random addresses are now computed on-the-fly instead of pre-computing them into a dynamically allocated buffer
- the above change also fixes a serious bug where fill_segment would silently give up and do nothing if the allocation failed
=> Refactor fill_segment code

src/argon2.c, src/encoding.c, src/encoding.h
This fixes some issues in Issue #143 that I didn't get fixed in PR #173 
Specifically this change
- Clarifies which function is responsible for setting which values (between `argon2_verify()` and `decode_string()`
- Improves memory error handling in `argon2_verify()`
- Changes `argon2_verify()` to use `argon2_verify_context()` so that the comparisons are always done with `argon2_compare()` which compares in constant time. Before, `argon2_verify()` was using `memcmp`, potentially exposing a side channel attack.
=> Cleaned up encoding issues

README.md
This PR addresses the concerns raised in #151 by clarifying the use for the `secret`, `ad`, and `flags` parameters in the low-level API. Note that in the discussion of the flags, it assumes the changes to the flags made in PR #176
=> Explain the use for the low-level API parameters

include/argon2.h
Noticed this is missing while updating the Python bindings.
=> Add doc for argon2_encodedlen's type parameter

README.md, man/argon2.1, src/run.c
Those flags allow one to make sure that the generated hashes are consistents over time even if the `argon2` binary is updated.
=> Allow setting Argon2 version number from the command-line

Makefile
The commit fixed #184, taking the "Fix 2" approach of dealing with the ABI Versioning.
This commit adds an `ABIVERSION` variable in the make file that should be incremented on every breaking change. Then, for Linux and macOS (Darwin), the name of the shared library is modified to include the version number. The unversioned shared library is then linked to this specific version.
As the install has gotten slightly more complicated, I also added an uninstall command for additional convenience. I also did a bit of formatting cleanup and set the correct permissions on the installed headers.
Tested on Ubuntu Linux (64 bit 3.13.0-105-generic) and macOS 10.11.6 (Darwin 15.6.0)
On linux:
Installed with `sudo make install`.
Compiled (with `gcc -Wall test.c -largon2 -o test`) and ran dynamically …
=> Shared library fix

latex/argon2-spec.tex
1. Fix allowed range of secret value K to match code.
2. Add type y for Argon2id.
=> Two small fixes to the spec

src/core.c
The index and value arguments to the G function are swapped in the comment.
=> Fix comment in fill_first_blocks.

src/argon2.c
On 64-bit architectures it is currently possible to have passwords that hash and verify to the same value, as demonstrated below:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "argon2.h"
int main(void) {
unsigned char out[32];
char encoded[108];
int ret;
const char pwd[] = "a not very long password";
const char salt[] = "a very long salt";
ret = argon2_hash(2, 1 << 16, 1, pwd, strlen(pwd), salt, strlen(salt), out,
sizeof(out), encoded, sizeof(encoded), Argon2_i, ARGON2_VERSION_13);
assert(ret == ARGON2_OK);
ret = argon2_verify(encoded, pwd, strlen(pwd), Argon2_i);
assert(ret == ARGON2_OK);
char * pwd2 = (char *)calloc(strlen(pwd) + (1ULL << 32) + 1, 1);
memset(pwd2, 'A', strlen(pwd) + (1ULL << 32));
memcpy(pwd2, pwd, strlen(pwd));
ret = …
```
=> Check for overflow on input lengths

src/encoding.c
Casting unsigned long to uint32_t is not guaranteed to be a safe operation as a long int can also be 64 bit wide and very often it is 64 bit wide. This change silences a couple of compiler warnings I got while building the code.
=> Fixed compiler warnings about potential dangerous casts

src/argon2.c
In [this `for` loop](https://github.com/P-H-C/phc-winner-argon2/blob/f15cf8bacd6594fdc51948959675bbf7d74666c3/src/core.c#L337), (reproduced below)
````c
uint32_t l;
for (l = instance->lanes - instance->threads; l < instance->lanes;
++l) {
if (argon2_thread_join(thread[l])) {
rc = ARGON2_THREAD_FAIL;
goto fail;
}
}
````
if `threads` is more than `lanes` (which is not specified to be illegal) `l` underflows. None of the threads will be joined and `argon2_ctx` may return before all the threads end, which means the `argon2_instance_t` instance is freed while threads are using it.
This mostly causes SIGSEGVs and SIGFPEs.
There doesn't seem to be any point if `threads` > `lanes` so just (silently) limiting `threads` to `lanes` fixes this.
=> Fix use after free if threads > lanes

src/core.h
The 'ALIGN' macro defined in core.h is not used anywhere, so it can be removed.
=> Remove unused ALIGN macro

README.md
So far the only python binding that enables keyed hashing.
=> Add link to another python binding: porridge

include/argon2.h, src/argon2.c, src/bench.c, src/blake2/blake2-impl.h, src/blake2/blake2.h, src/blake2/blake2b.c, src/blake2/blamka-round-opt.h, src/blake2/blamka-round-ref.h, src/core.c, src/core.h, src/encoding.c, src/encoding.h, src/genkat.c, src/genkat.h, src/opt.c, src/ref.c, src/run.c, src/test.c, src/thread.c, src/thread.h
Trivial commit (no functional change) but git often prints a lot of warnings if a source file is copied to another project.
It is better to remove it in the source project :)
=> Fix trailing spaces in source headers (to remove git warning).

include/argon2.h
It doesn't allocate the memory at @hash!
=> Fix up documentation for argon2i_hash_raw

src/run.c
Creating test hashes for [node-argon2](https://github.com/ranisalt/node-argon2) I noticed the CLI tool does not have the ability to hash passwords containing null characters. As this is easily fixable by getting the password length from the call to `fread` instead of `strlen`, I made the change.
Additionally, it does not trim trailing newlines anymore.
=> Allow null character in password for cli tool

src/run.c
to fix https://github.com/P-H-C/phc-winner-argon2/issues/211
This is the simplest patch I could think of. Let me know whether/how I should add tests for it (i.e. should I change the way all existing tests are using m_cost, or add some new cases, or something else).
The mnemonic I have for `-k` is "KiBs of memory" - suggestions for a different letter are welcome.
=> add support for fine-grained memory setting

Makefile
=> Don't include 'clean' target in 'make all' to fix parallel builds

src/core.c, src/genkat.c, src/run.c, src/test.c
Fixes #205 and removes some includes that weren't necessary. Since the only required macro from that file was `PRIu32` I copied it to the file that needed it.
=> Remove dependency of inttypes.h

Makefile
Before commit 5e78398c (Added ABI Version Number, and properly handle
it for Linux and Darwin) the library was installed as `libargon2.so`,
though the soname was `libargon2.so.0`. Actually installing a package
with that file makes `ldconfig` create a symbolic link matching the
soname. That file does not  belong to the package and is not managed by
the package manager.
Building a package from current git master results in the library file
`libargon2.so.0` being included in the package. That conflicts with the
file formerly created by `ldconfig`.
So bump the ABI version for a conflict-free transition to current code.
=> bump ABI version

README.md
Hi,
I've written a high-level Java API for Argon2 password hashing (https://github.com/kosprov/jargon2-api). 
It allows interchangeable back-ends and one of them binds to the RI.
Regards,
K
=> Additional JVM bindings (Jargon2)

README.md
A few days ago i started building an Argon2 Erlang binding called eArgon2.
It's in his early beta stages, however it's working and bypassed simple tests. I added my binding to the binding list alphabetically (i noticed all are listed alphabetically). Please accept my listing. Thank's!
=> Added Argon2 Erlang binding.

README.md
Also I couldn't find the "low-level API" functions `argon2i`, `argon2d`, and `argon2id`. Were these removed or did I not look hard enough?
=> Spelling and updated function name changes

Argon2.sln, vs2015/Argon2Opt/Argon2Opt.vcxproj, vs2015/Argon2OptBench/Argon2OptBench.vcxproj, vs2015/Argon2OptDll/Argon2OptDll.vcxproj, vs2015/Argon2OptGenKAT/Argon2OptGenKAT.vcxproj, vs2015/Argon2OptTestCI/Argon2OptTestCI.vcxproj, vs2015/Argon2Ref/Argon2Ref.vcxproj, vs2015/Argon2RefBench/Argon2RefBench.vcxproj, vs2015/Argon2RefDll/Argon2RefDll.vcxproj, vs2015/Argon2RefGenKAT/Argon2RefGenKAT.vcxproj, vs2015/Argon2RefTestCI/Argon2RefTestCI.vcxproj
There are two improvements here. First, drop the minimum requirement for Visual  Studio to 2010 (Toolset version 10.00). This allows someone to open and run the project with VS2010, 201 2, 2013, 2015, 2017, 2019, etc. Whatever they have on their machine works, and they won't encounter "wrong toolset" errors (or similar). Second, enable debugging in formation so the code can be stepped under Visual Studio.
-----
This change came about due to testing on Windows 8.1 with Visual Studio 2010, 2012 and 2013 installed. The solution failed to compile because I lacked Visual Studio 2015 (Toolset version 14.00). I have Visual Studio 2015, 2017 and 2019 on a Windows 10 machine, but I despise working on Windows 10. It was better for me to fix the project files in a way so they "just work" everywhere. …
=> Visual Studio improvements

README.md
I've published an Android binding named [Argon2Kt](https://github.com/lambdapioneer/argon2kt) for Argon2 that makes it simple for Android developers to use Argon2. It emerged from a personal mobile app project.
Looking at the existing bindings I've found that the existing Java bindings don't work too well with Android - especially with the now mandatory 64-bit support. Argon2Kt can be used from both Kotlin and Java projects.
I hope adding to the listing will help other mobile developers.
=> Adding new Android binding to README.md

include/argon2.h
In order to determine how to set up the ARGON2_PUBLIC and ARGON2_LOCAL
macros, we check for various different environments via preprocessor
defines. For Microsoft Visual Studio, we check that the macro _MSC_VER
evaluates to non-zero via `#elif _MSC_VER`. This may raise a compile
error when compiling with "-Werror=undef" if the variable isn't defined.
Fix the issue by using `#elif defined(_MSC_VER)` instead.
=> Fix possible compiler error due to undefined _MSC_VER

Makefile
When building libargon2 as part a buildsystem like for example buildroot (which targets embedded systems), it shouldn't fail if the symlink is already present on the target rootfs.
=> Don't fail on existing symlink

Makefile
Some Linux distributions (e.g. NixOS, where this issue was spotted) don't provide an unprefixed ar when cross-compiling. This PR aims to fix this.
See [NixOS/nixpkgs#67490](https://github.com/NixOS/nixpkgs/pull/67490) for information on where did it start.
=> Fix cross-compilation on some Linux systems

src/bench.c, src/blake2/blake2-impl.h, src/core.c, src/genkat.c
These are drawn from patches in https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-argon2, with corrections.
`_MSC_VER` is defined specifically by the Microsoft C compiler and should be used for code _specific to that compiler, not Windows_. `_WIN32` is defined by any C compiler targeting Windows *automatically* - i.e. both the Microsoft C compiler and mingw-w64 GCC define it.
=> mingw-w64 / MSYS2 fixes

README.md
Hello! I recently created the Dart bindings for Argon2: [dargon2](https://github.com/tmthecoder/dargon2). It is also published to Dart [pub.dev](https://pub.dev/packages/dargon2). Would you be able to merge the request to add it to the README?
Thank you!
=> Add dargon2 (Dart) bindings to the README

README.md
I was a tad confused while looking through the readme, since the example shows setting the variable to `2` for a `1-pass computation`. I believe this makes it correct.
=> Fix comment in code shown in the README.
