P-H-C/phc-winner-argon2

Makefile, kats/check-sums.sh
I think this should be converted to autotools and libtool instead (and I'm willing to help with that), but this is makes it at least build on NetBSD.
=> Add NetBSD support.

src/run.c
This fix a compilation error on my linux box
=> fread() return a size_t

src/argon2.c
https://cryptocoding.net/index.php/Coding_rules#Problem
=> Avoid memcmp() for hash verification

src/encoding.h
Also makes consistent with other headers.
=> Prevent duplicate encoding includes.

src/argon2.c
I wrote this somewhat broken unit test, complete with out of order arguments:
ret = argon2i_verify("password", "$argon2i$m=65536,t=2,p=1$c29tZXNhbHQAAAAAAAAAAA$iUr0/y4tJvPOFfd6fhwl20W04gQ56ZYXcroZnK3bAB4", strlen("password"));
if(ret == ARGON2_OK)
printf("Somehow returned SUCCESS\n");
Despite obviously broken input, the argon2i verifier insisted the password was valid and kept printing that SUCCESS message.
These checks address that issue.
=> Mange decoding fails.

src/encoding.c
Edit: Alternatively this may make more sense to be refactored as a while() loop. Let me know if you'd prefer.
=> Remove assignment which is also made on line 202.

README.md
Accidentally the links and link texts were inverted on Markdown :laughing: additionally I linked to profiles on the user handles.
=> Fix bindings links

README.md
=> Link to Rust bindings

README.md
Hi,
i've written a binding for the JVM and added the link it to the readme.
=> Added binding for the JVM.

README.md
Wrote some Lua binding.
Also proposed to add Argon2 to Homebrew: Homebrew/homebrew#48019, we'll see how it goes!
=> docs(readme) add Lua binding

src/argon2.c, src/encoding.c
A recent commit appears to have introduced a number of tabs. This led to unusual viewing in different editors.
=> Remove a mix of tabs and spaces.

src/core.c
Addresses a minor memory leak.
=> Free memory on thread failure.

src/run.c
Added command line options -e and -r.  With -e, you will get only the encoded output, e.g.:
$argon2i$v=19$m=65536,t=3,p=1$dGVzdGFiY2Q$yz3j1twZfVhuhgQmW8MNAPc3qz/9uArczAkrqsdgDLM
With -r, you will get only the hexadecimal of the raw hash (similar to the output of md5sum), e.g.:
cb3de3d6dc197d586e8604265bc30d00f737ab3ffdb80adccc092baac7600cb3
=> Add options for bare output to executable

Makefile
I added build support for Solaris in the Makefile.
=> Solaris build support

src/argon2.c, src/run.c
Compares against UINT32_MAX as discussed.
=> Safer implementation of #135.

Argon2.sln, vs2015/Argon2Opt/Argon2Opt.vcxproj, vs2015/Argon2OptBench/Argon2OptBench.vcxproj, vs2015/Argon2OptDll/Argon2OptDll.vcxproj, vs2015/Argon2OptDll/Argon2OptDll.vcxproj.filters, vs2015/Argon2OptGenKAT/Argon2OptGenKAT.vcxproj, vs2015/Argon2Ref/Argon2Ref.vcxproj, vs2015/Argon2RefBench/Argon2RefBench.vcxproj, vs2015/Argon2RefDll/Argon2RefDll.vcxproj, vs2015/Argon2RefDll/Argon2RefDll.vcxproj.filters, vs2015/Argon2RefGenKAT/Argon2RefGenKAT.vcxproj, vs2015/Argon2RefTestCI/Argon2RefTestCI.vcxproj
Includes 2 new projects outputting DLLs and a new Configuration ReleaseStatic for creating binaries which only rely on kernel32.dll
=> Easier Windows DLL building + dependency-less builds

Makefile
I updated the makefile so that the library will build under Cygwin.
=> updated makefile to build under Cygwin environment

README.md
Added details of an Elixir library with bindings for Argon2 to the README.
=> Added details of Elixir implementation

src/core.c
=> avoid thread creation in p=1 case

Makefile, src/core.c, src/thread.c, src/thread.h
As suggested by Joseph Richey in #187, this adds support for a situation where threads may not be available for one reason or another.
=> add support for no threading

README.md
Not to be confused with the ruby binding :)
=> add mruby binding

src/test.c
Hi,
With Argon2_id gaining popularity, it should be included in the tests.
=> Add tests for Argon2_id.

LICENSE, Makefile, README.md, include/argon2.h, src/argon2.c, src/bench.c, src/blake2/blake2-impl.h, src/blake2/blake2.h, src/blake2/blake2b.c, src/blake2/blamka-round-opt.h, src/blake2/blamka-round-ref.h, src/core.c, src/core.h, src/encoding.c, src/encoding.h, src/genkat.c, src/genkat.h, src/opt.c, src/ref.c, src/run.c, src/test.c, src/thread.c, src/thread.h
Signed-off-by: Francesco Turco <mail@fturco.net>
=> use HTTPS instead of HTTP for URLs
